# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-13 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
