# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='insects.Appearance')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('is_maximum', models.BooleanField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='insects.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('kind', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='insects.Process')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='insects.Process')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='insects.Process'),
        ),
        migrations.AddField(
            model_name='clip',
            name='frames',
            field=models.ManyToManyField(related_name='clips', to='insects.Frame'),
        ),
        migrations.AddField(
            model_name='clip',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='insects.Process'),
        ),
        migrations.AddField(
            model_name='classificationvalue',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_values', to='insects.Species'),
        ),
        migrations.AddField(
            model_name='classification',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='insects.Process'),
        ),
        migrations.AddField(
            model_name='classification',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='insects.Tracking'),
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundingboxes', to='insects.Process'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='boundingbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='insects.BoundingBox'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='insects.Frame'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='insects.Process'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='insects.Tracking'),
        ),
    ]
