# Generated by Django 2.2.8 on 2020-01-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='frames',
        ),
        migrations.AddField(
            model_name='collection',
            name='frames',
            field=models.ManyToManyField(related_name='collections', to='insects.Frame'),
        ),
    ]
